### ISSUE TITLE
Improving Git Modularity

### ISSUE THREAD

**Issue by lucienpeach** [weinitor/Kinegami#13]
Includes rearranging file structure to improve readability and publishing official v1.0.

**Comment by weinitor** [comment]
Change is required

- move DubinsPlot.m to "Visualisation"
- move DubinTube.m to "Kinegami"
- change "schematic plotting" to Crease-Pattern-Plotting"
- change - to _
- fix submodule

**Comment by weinitor** [comment]
- Remove KinegamiAPP, (add it to another branch, maybe "dev"?)
- remove Kinegami_hopper_template.m

**Comment by weinitor** [comment]
- rename Origami library to Tubular-Origami-Catalogue for better referencing

**Comment by weinitor** [comment]
- I think we don't need to change "-" to "_", since one of our submodules uses "-" in "Bounding-Spheres-And-Circles".
- Also, I think I wrote the GenerateDXF.m function. But it's just a common function to use, maybe we can just take out the authors section? What do you think? In addition, should we rename the folder "DXF-Function" "Misc"?

**Comment by lucienpeach** [comment]
Changes implemented. See #15.
